### ISSUE TITLE
Feedback on Milestone 2

### ISSUE THREAD

**Issue by nuranskitchen** [UBC-MDS/student_performance#21]
@zxzzhangg and @YenanZ, great job on Milestone 2! Here are some remaining issues:

- [ ] Include instructions on how to run your analysis with make on the main readme
- [ ] Add links to the specific folders you mention in "Repo structure" section on the readme

**Suggestions:**

- [ ] Go through http://swcarpentry.github.io/make-novice/reference. This would help you make your Make code more practical. For example, you can use automatic variables and avoid some repetition.

**Comment by YenanZ** [comment]
The changes has been incorporated
